name: Chatops
on: issue_comment
jobs:
  chatops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          reactions: true
          config-from-file: .github/chatops.json
          commands: deliver,deploy,enforcer,figma,gcr,lgtm,sync,test
