name: Milestone
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: 1
            })
