name: Sentry
on: release
jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: tclindner/sentry-releases-action@master
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: sentrei
          SENTRY_PROJECT: sentrei
        with:
          tagName: ${{ github.ref }}
          environment: main
