name: Sync
on:
  repository_dispatch:
    types: [sync-cmd]
  schedule:
    - cron: "0 0,8,16 * * *"
jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
        branch: [alpha, beta, main]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - if: matrix.branch != 'main'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch --quiet && git merge --ff-only origin/main && git push || true
      - if: matrix.branch == 'main'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:sentrei/sentrei.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_KEY }}
      # - if: matrix.branch == 'main'
      #   uses: peter-evans/dockerhub-description@v2
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     DOCKERHUB_REPOSITORY: ${{ github.repository }}
